# Generated by Django 5.0.7 on 2024-08-10 15:48

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_baseuser_phone_number_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('password', models.CharField(max_length=6, null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 10, 15, 50, 27, 177088, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'One Time Password',
                'verbose_name_plural': 'One Time Passwords ',
            },
        ),
    ]
