# Generated by Django 5.0.7 on 2024-08-11 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('phone_number', models.CharField(max_length=13)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='otprequest',
            name='password',
        ),
        migrations.RemoveField(
            model_name='otprequest',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='otprequest',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='otprequest',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='otprequest',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='otprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='otprequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
