# Generated by Django 5.0.7 on 2024-08-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_otprequest_user_otprequest_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
